---
abstract: 'git-compatible config file parsing'
author:
  - 'Best Practical Solutions, LLC'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  File::Temp: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-GitLike
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bestpractical/config-gitlike
version: 1.04
