---
abstract: 'git-compatible config file parsing'
author:
  - 'Best Practical Solutions, LLC'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-GitLike
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moo: 0
  MooX::Types::MooseLike: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bestpractical/config-gitlike
version: 1.13
